name: CI Deployment

on:
    push:
        branches: [main]

    workflow_dispatch:

env:
  region: us-east-1
  FRONTEND_REPOSITORY: skillpulse-frontend
  BACKEND_REPOSITORY: skillpulse-backend

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
# BACKEND
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download Go Modules
        working-directory: backend
        run: go mod download

      - name: Run Backend Tests
        working-directory: backend
        run: go test ./...

#AWS LOGIN
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
          aws-region: ${{env.region}}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

# Build & Push Backend Image
      - name: Build Backend Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPOSITORY }}:${{ github.sha }} ./backend

      - name: Push Backend Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPOSITORY }}:${{ github.sha }}

# Build & Push Frontend Image

      - name: Build Frontend Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }} ./frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }}