name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.sha }}

      - name: Update Kubernetes deployment manifest
        run: |
          sed -i "s|image: ${env.DOCKERHUB_USERNAME}/skillpulse-backend:.*|image: ${env.DOCKERHUB_USERNAME}/skillpulse-backend:${GITHUB_SHA}|"  k8s/3-backend.yml
          sed -i "s|image: ${env.DOCKERHUB_USERNAME}/skillpulse-frontend:.*|image: ${env.DOCKERHUB_USERNAME}/skillpulse-frontend:${GITHUB_SHA}|" k8s/4-frontend.yml

      - name: Commit updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add k8s/3-backend.yml
          git add k8s/4-frontend.yml

          git commit -m "Update image tag to ${GITHUB_SHA}" || echo "No changes"

          git push
